project:
  type: website

website:
  title: "Lukas Jung"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme: theme.scss
    css: styles.css

editor: visual
